default:
  image: git.haw-hamburg.de:5005/wp-webbrowser-browser-frosted/frosted-browser/project-python:latest
  cache:
    paths:
      - ~/.cache/pip/
stages:
  - build
  - test
lint:
  stage: build
  script:
    - flake8 --ignore=E501,W503 --per-file-ignores="__init__.py:F401" .
python-unit-tests:
  stage: test
  script:
    - coverage run --omit *__init__.py,*test/* -m unittest discover -s test -p "Test*.py"
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml